[package]
name = "calculator"
version = "1.0.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.2.1", features = ["server", "transport-io"] }
serde = "1.0.219"
tokio = { version = "1.46.0", features = ["rt-multi-thread"] }
